services:
  media-library-manager:
    container_name: media-library-manager
    image: ghcr.io/leolionart/media-library-manager:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - HOST=0.0.0.0
      - PORT=9988
      - STATE_FILE=/app/data/app-state.json
    volumes:
      - ./data:/app/data
      - /mnt:/mnt:ro
      - /media:/media:ro
      - /srv:/srv:ro
