services:
  media-library-manager:
    container_name: media-library-manager
    image: ghcr.io/leolionart/media-library-manager:latest
    restart: unless-stopped
    ports:
      - 9988:9988
    environment:
      - STATE_FILE=/app/data/app-state.json
    volumes:
      - ./data:/app/data
      # Change these paths to match your host folders (e.g., /volume1/video on Synology)
      - /mnt:/mnt:ro
      - /media:/media:ro
      - /srv:/srv:ro
